'''
Problem ID:
0002

Problem Title:
Even Fibonacci numbers

Problem Description:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Problem Solution:
4613732
'''

def fibonacci(N):
    if N==0 or N==1:
        return 1
    else:
        return fibonacci(N-1)+fibonacci(N-2)

def solution():
    N=1               # starting with 1
    total=0           # initializing total
    last_fibonacci=1  # initializing last fibonacci
    while last_fibonacci<4000000:
        if last_fibonacci%2==0:
            total+=last_fibonacci
        N+=1
        last_fibonacci=fibonacci(N)
    return total

print(solution())