'''
Problem ID:
PE0012

Problem Title:
Highly divisible triangular number

Problem Description:
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

Problem Solution:

'''
import time
from primality import primality as prim

def detFactors(number):
    factors = [number,1]
    for factor in range(2,number):
        if number%factor==0:
            factors.append(factor)
    factors.sort()
    return factors

def triangNumber(n):
    return (n**2+n)/2

def solution(target):
    result = 0
    factors = [1]
    n = 1
    while len(factors)<target:
        n += 1
        result = round(triangNumber(n))
        factors=detFactors(result)
    return result

timer=time.time()
print(solution(500))
print(f'It took {round(time.time()-timer,4)} secs')